# This file was generated by GoReleaser. DO NOT EDIT.
class Tl < Formula
  desc "verify https assets with a public transparency log"
  homepage "https://www.transparencylog.com/"
  version "0.2.11"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/transparencylog/tl/releases/download/v0.2.11/tl_0.2.11_darwin_x86_64.tar.gz"
    sha256 "b9b695f844eb5ab83e384783fcc7477725e190068d6b8073cd7b3bb96392e017"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/transparencylog/tl/releases/download/v0.2.11/tl_0.2.11_linux_x86_64.tar.gz"
      sha256 "9a49a5e668baaa623bb31177b16ca766ad20a6cef434fe9db4f1f2179e507870"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/transparencylog/tl/releases/download/v0.2.11/tl_0.2.11_linux_arm64.tar.gz"
        sha256 "b5e6821f058f52ad407bc2a1e4d61a27fc0aef88d2558733afdae399737bf5f6"
      else
        url "https://github.com/transparencylog/tl/releases/download/v0.2.11/tl_0.2.11_linux_armv6.tar.gz"
        sha256 "c435dcb279f72ad2c24b47c233b53c47bcfe0cc56475500f8a579621be17df17"
      end
    end
  end

  def install
    bin.install "tl"
  end
end
