# This file was generated by GoReleaser. DO NOT EDIT.
class Tl < Formula
  desc "verify https assets with a public transparency log"
  homepage "https://www.transparencylog.com/"
  version "0.2.12"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/transparencylog/tl/releases/download/v0.2.12/tl_0.2.12_darwin_x86_64.tar.gz"
    sha256 "730507e381a6a808831c10072d7f74156dad647109c8754e7fab46aaea4c3e57"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/transparencylog/tl/releases/download/v0.2.12/tl_0.2.12_linux_x86_64.tar.gz"
      sha256 "dcc53c3c61f3faf1f6451e38e1f9fde7f71b03df0a7d4ff261643f267dddf5be"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/transparencylog/tl/releases/download/v0.2.12/tl_0.2.12_linux_arm64.tar.gz"
        sha256 "6321d2e6b6e9dce0ac8b6b4245b0f29e8d4f3877307c0fb8b209013010007abb"
      else
        url "https://github.com/transparencylog/tl/releases/download/v0.2.12/tl_0.2.12_linux_armv6.tar.gz"
        sha256 "b264fe6e00d063b9adc4532912c7e62bc32998452df148e93d2d105003c6fe2c"
      end
    end
  end

  def install
    bin.install "tl"
  end
end
